### ISSUE TITLE
OCPI: Small refactoring tracking

### ISSUE THREAD

**Issue by LucasBrazi06** [LucasBrazi06/ev-dashboard#1545]
As discuss in your PRs, I created this issue to track the changes:

**Backend**
- [x] Type the following props in OCPIEndpoint:
  - businessDetails?: any;
  - availableEndpoints?: any;

- [ ] Create a specifics HTTP type.
Check also that all methods should return type (eg. filterOcpiEndpointDeleteRequest, ...)
Mobule: OCPIEndpointSecurity.ts

- [ ] OCPIJobResult should extends ActionsReponse for inError/inSuccess

**Front-end**
- [ ] Move all the code related to the buttons in the button's class (eg.: TableDeleteAssetAction). To be done in all OCPI buttons.

**Comment by LucasBrazi06** [comment]
@ellavas , update the checkboxes above if you have implemented some

**Comment by ellavas** [comment]
not yet

**Comment by fcoutellier** [comment]
Linked to issue 1650. Please proceed this. @jerome-benoit : Issue after the 1650.
